### ISSUE TITLE
Vytvorit katalog poziadaviek

### ISSUE THREAD

**Issue by efka218** [TIS2016/Roboticka-Liga#1]
Podla standardu IEEE/ANSI 830 vytvorit dokument

**Comment by Foltyn5** [comment]
Specifikacie je kompletna v pdf formate na githube

**Comment by pavelpetrovic** [comment]
navrhujem neponahlat sa so zatvaranim issues. 
myslim, ze najskor treba, aby ten dokument videl cviciaci a potom k nemu moze mat pripomienky aj zadavatel a az ked vsetky tie budu upravena a dokument akceptovany, potom bude tento issue v stlpceku "Done" a zrely, aby ho ten, ktory sa stara vo vasej skupine o pracu presunul do closed.

**Comment by pavelpetrovic** [comment]
nezabudnite, prosim, pouzivat zenhub.

**Comment by Foltyn5** [comment]
Rozumiem, ďakujem za upozornenie.
