### ISSUE TITLE
Vytvorenie entitno-relačného diagramu

### ISSUE THREAD

**Issue by efka218** [TIS2016/Roboticka-Liga#2]
http://www.kiwiki.info/index.php/Entitno_-_Rela%C4%8Dn%C3%BD_Diagram

**Comment by pavelpetrovic** [comment]
preposielam to aj sem:

pozor, tato linka nie je OK, upozornoval som uz trochu a hlavne budeme
to brat az v utorok, ze ERD, ktory treba spravit nema byt datovy model,
ale taketo nieco:

http://www.texample.net/media/tikz/examples/PNG/entity-
relationship-diagram.png

viac k tomuto na prednaske.

**Comment by efka218** [comment]
Ok dakujem za upozornenie.

2016-10-09 4:25 GMT+02:00 Pavel Petrovič notifications@github.com:

> preposielam to aj sem:
> 
> pozor, tato linka nie je OK, upozornoval som uz trochu a hlavne budeme
> to brat az v utorok, ze ERD, ktory treba spravit nema byt datovy model,
> ale taketo nieco:
> 
> http://www.texample.net/media/tikz/examples/PNG/entity-
> relationship-diagram.png
> 
> viac k tomuto na prednaske.
>
