### ISSUE TITLE
Diagram komponentov 

### ISSUE THREAD

**Issue by efka218** [TIS2016/Roboticka-Liga#6]
Diagram komponentov popisuje, ako je softvérový systém rozdelený do fyzických komponentov, ako napríklad súborov, hlavičiek, linkovaných knižníc, modulov, spustiteľných programov, balíčkov a zobrazuje závislosti medzi nimi.

**Comment by pavelpetrovic** [comment]
To je len jedno z moznych cleneni, ktore moze zobrazit, aj ked na toto by
bolo lepsie pouzit skor package diagram. Skuste primarne vychadzat vzdy z
nasich materialov
http://dai.fmph.uniba.sk/courses/tvorbaIS/tis/new.html

Tu chceme vidiet skor na ake logicke casti mozeme rozdelit system, ked uz
bezi (podla funkcionality) ako na casti podla ktorych je rozdelena
implementacia.
