### ISSUE TITLE
Data model

### ISSUE THREAD

**Issue by efka218** [TIS2016/Roboticka-Liga#7]
https://en.wikipedia.org/wiki/Data_model

**Comment by pavelpetrovic** [comment]
Tato linka vam velmi nepomoze, kedze je to velmi vseobevny pojem, je tam
toho zbytocne vela. Mame na mysli hlavne relacny model databazy, niekedy sa
mu hovori aj erd - ten druhy typ. Najlepsie je ho vytvorit priamo z
databazy napr. cez phpmyadmin, ktorybna kempelenovi bezi, idem vam spravit
to slubene prostredie konecne...
