### ISSUE TITLE
Náčrt interfacu pri hodnotení týmov

### ISSUE THREAD

**Issue by efka218** [TIS2016/Roboticka-Liga#8]
čo sme sa bavili ze moodle to ma podobne atd.

**Comment by pavelpetrovic** [comment]
pouzivajte na kreslenie diagramov aj pouzivatelskeho rozhrania nejake
sikovne nastroje - je ich na internete mnozstvo,
napr. draw.io

p.

**Comment by pavelpetrovic** [comment]
v tomto konkretnom pripade je to ten "mockup" alebo "wireframe"

(teda ak som pochopil, ze tento issue je o pouzivatelskom rozhrani...) :-)
